[pytest]
pythonpath = src
testpaths = tests

addopts = 
    --cov=usso_jwt
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=100

filterwarnings =
    ignore:.*pkg_resources.*:DeprecationWarning
